version: '3'

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
      
  external:
    image: immfly/external-service
    ports:
      - "8085:8085"
    restart: always
    environment:
      SERVER_PORT: "8085"
    
  immfly:
    image: immfly/flight-service
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - redis
      - external
    environment:
      SPRING_PROFILES_ACTIVE: 'prod'
   
