version: '3'

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'

  immfly:
    image: immfly/flight-service
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: 'prod'
